%To run the encoding 
commandStr = 'python3 SAE/encode.py';
[status, commandOut] = system(commandStr);
if status==0 
Msg = commandOut ;
end
Wsm_request = struct('Channel_Identifier' ,178 , ...
'Data_Rate' , 120 ,...
'Transmit_Power_Level' ,  0 , ...
'Channel_Load' , '0000' , ...
'Info_Elements_Indicator', '0000' , ...
'User_Priority' , 2 , ...
'Expiry_Time', 200 , ...
'Length' , length(Msg), ...
'Data', Msg , ...
'Peer_MAC_Address', 'FF:FF:FF:FF:FF:FF' , ... 
'Provider_Service_Identifier', '87' ) ;
DL_UNIT_DATA_X = DL_UNIT_DATA_X_creator(Wsm_request) ;
MA_UNIT_DATA_X = MA_UNIT_DATA_X_creator(DL_UNIT_DATA_X) ;
MPDU = MACencapsulate('Data','Data', true, true, MA_UNIT_DATA_X);